[Desktop Entry]
Name=Plank Player
Name[ca]=Plank Player
Name[ca@valencia]=Plank Player
Name[cs]=Plank Player
Name[de]=Plank Player
Name[en_GB]=Plank Player
Name[es]=Plank Player
Name[eu]=Plank Player
Name[fi]=Plank Player
Name[fr]=Plank Player
Name[hi]=प्लॅन्क-प्लॅयर
Name[hu]=Plank Player
Name[it]=Plank Player
Name[ka]=Plank Player
Name[ko]=Plank Player
Name[nl]=Plank Player
Name[nn]=Plank Player
Name[pl]=Plank Player
Name[pt]=Plank Player
Name[pt_BR]=Plank Player
Name[ro]=Plank Player
Name[sk]=Plank Player
Name[sl]=Plank Player
Name[sv]=Plank Player
Name[tr]=Plank Oynatıcı
Name[uk]=Plank Player
Name[x-test]=xxPlank Playerxx
Name[zh_CN]=Plank Player
MimeType=@DesktopMimeType@
Exec=@DesktopExec@
Icon=plank-player
Type=Application
NoDisplay=@DesktopNoDisplay@
GenericName=PlankPlayer
GenericName[ca]=Plank Player
GenericName[ca@valencia]=Plank Player
GenericName[cs]=Plank Player
GenericName[de]=Plank Player
GenericName[en_GB]=Plank Player
GenericName[es]=Plank Player
GenericName[eu]=Plank Jotzailea
GenericName[fi]=Plank Player
GenericName[fr]=Plank Player
GenericName[hi]=प्लॅन्क-प्लॅयर
GenericName[hu]=Plank Player
GenericName[it]=Plank Player
GenericName[ka]=Plank Player
GenericName[ko]=Plank Player
GenericName[nl]=Plank Player
GenericName[nn]=Plank Player
GenericName[pl]=Plank Player
GenericName[pt]=Plank Player
GenericName[pt_BR]=Plank Player
GenericName[ro]=Plank Player
GenericName[sk]=Plank Player
GenericName[sl]=Plank Player
GenericName[sv]=Plank Player
GenericName[tr]=Plank Oynatıcı
GenericName[uk]=Plank Player
GenericName[x-test]=xxPlank Playerxx
GenericName[zh_CN]=Plank Player
Categories=AudioVideo;Player;
Keywords=program;multimedia;Player;
Keywords[ca]=programa;multimedia;reproductor;
Keywords[ca@valencia]=programa;multimedia;reproductor;
Keywords[cs]=program;multimédia;přehrávač;
Keywords[de]=medien;spieler;
Keywords[en_GB]=program;multimedia;Player;
Keywords[es]=programa;multimedia;Reproductor;
Keywords[eu]=programa;multimedia;Player;Jotzailea;
Keywords[fi]=ohjelma;multimedia;soitin;
Keywords[fr]=programme ; multimedia ; lecteur ;
Keywords[hi]=कार्यक्रम;मल्टीमीडिया;प्लॅयर;
Keywords[hu]=program;multimédia;Lejátszó;
Keywords[it]=programma;multimedia;lettore;
Keywords[ka]=პროგრამა;მულტიმედია;დამკვრელი;
Keywords[ko]=program;multimedia;Player;프로그램;멀티미디어;재생기;
Keywords[nl]=programma;multimedia;afspeler;
Keywords[nn]=program;multimedia;spelar;
Keywords[pl]=program;multimedia;odtwarzacz;
Keywords[pt]=programa;multimédia;Leitor;
Keywords[pt_BR]=programa;multimídia;reprodutor;tocador;
Keywords[ro]=program;multimedia;lector;
Keywords[sk]=program;multimédiá;prehrávač;
Keywords[sl]=program;multimedija;Predvajalnik;
Keywords[sv]=program;multimedia;spelare;
Keywords[tr]=program;çoklu ortam;oynatıcı;
Keywords[uk]=program;multimedia;Player;програма;мультимедіа;звук;відео;програвач;
Keywords[x-test]=xxprogramxx;xxmultimediaxx;xxPlayerxx;
Keywords[zh_CN]=program;multimedia;Player;程序,多媒体;播放器
